fix(set-reset-cookie): add missing cc target for cooke_config_proto to BUILD (#370)
Fixes BUILD file bug looking for
'//samples/set_reset_cookie:cookie_config_cc_proto' target, as well as
invalid proto include in plugins.cc.

Plugins test (Bazel test) fails to build with
```
ERROR: /home/runner/work/service-extensions/service-extensions/plugins/samples/set_reset_cookie/BUILD:37:22: in deps attribute of cc_binary rule //samples/set_reset_cookie:proxy_wasm_plugin_cpp: target '//samples/set_reset_cookie:cookie_config_cc_proto' does not exist. Since this rule was created by the macro 'proxy_wasm_plugin_cpp', the error might have been caused by the macro implementation
ERROR: /home/runner/work/service-extensions/service-extensions/plugins/samples/set_reset_cookie/BUILD:37:22: Analysis of target '//samples/set_reset_cookie:proxy_wasm_plugin_cpp' failed
ERROR: Analysis of target '//samples/set_reset_cookie:plugin_cpp.wasm' failed; build aborted: Analysis failed
INFO: Elapsed time: 189.853s, Critical Path: 0.70s
INFO: 163 processes: 49 disk cache hit, 114 internal.
ERROR: Build did NOT complete successfully
```

- [X] Tests pass
- [X] Appropriate changes to documentation are included in the PR